### ISSUE TITLE
Unable to create virtual environment

### ISSUE THREAD

**Issue by wandesky** [tibetegya/WeConnect#5]
I tried running the command `virtualenv ENV` after cloning your repo but it generates an error 

> The term 'virtualenv' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by tibetegya** [comment]
Virtualenv is  a package I installed bacause it does not come with python

Did you first install the requirements.txt?
If not.... Install it first by running "pip install -r requirements.txt"

Virtualenv is among the dependancies

**Comment by tibetegya** [comment]
Or install it with

Pip install virtualenv
